name: midp
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - transformers==4.46.3
      - accelerate
      - datasets
      - huggingface_hub
      - pillow
      - pyyaml
      - scikit-learn
      - tqdm
      - pyarrow
      - pandas
